name: "C CI"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Install dependencies"
      run: sudo apt-get install -y gcc cppcheck

    - name: "Compile C code"
      run: |
        gcc -o my_program new.c

    - name: "Run cppcheck"
      run: |
        cppcheck --enable=all --inconclusive --error-exitcode=1 .

    - name: "Run tests"
      run: |
        ./my_program