name: "C CI"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Install dependencies"
      run: sudo apt-get install -y gcc 

    - name: "Compile C code"
      run: |
        gcc -c  new.c

    - name: "Run tests"
      run: |
        ./a.c