name: "code check by flake 8"
on: ["push","pull"]
runs-on: ubuntu-latest
  jobs: 
    steps:
      -name: "checkout"
        uses: actions/checkout@v2
      -name: "installing python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      -name: "flake8"
        run: "pip install flake8"
        run: "flake8 ."
        



